services:
  moya_db:
    build:
      context: /Users/clr/moya_db
    container_name: moya_db
    ports:
      - "9000:9000"

  manager:
    build:
      context: .
    image: moya_squeezer:latest
    container_name: moya_squeezer_manager
    hostname: manager
    depends_on:
      - moya_db
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    command:
      [
        "elixir",
        "--name",
        "manager@manager",
        "--cookie",
        "squeeze_cookie",
        "-S",
        "mix",
        "squeezer.run",
        "config/docker.toml",
        "--role",
        "manager",
        "--worker",
        "worker1@worker1",
        "--worker",
        "worker2@worker2",
        "--worker",
        "worker3@worker3"
      ]

  worker1:
    image: moya_squeezer:latest
    container_name: moya_squeezer_worker1
    hostname: worker1
    depends_on:
      - manager
    restart: on-failure
    command:
      [
        "elixir",
        "--name",
        "worker1@worker1",
        "--cookie",
        "squeeze_cookie",
        "-S",
        "mix",
        "squeezer.run",
        "--role",
        "worker",
        "--manager",
        "manager@manager"
      ]

  worker2:
    image: moya_squeezer:latest
    container_name: moya_squeezer_worker2
    hostname: worker2
    depends_on:
      - manager
    restart: on-failure
    command:
      [
        "elixir",
        "--name",
        "worker2@worker2",
        "--cookie",
        "squeeze_cookie",
        "-S",
        "mix",
        "squeezer.run",
        "--role",
        "worker",
        "--manager",
        "manager@manager"
      ]

  worker3:
    image: moya_squeezer:latest
    container_name: moya_squeezer_worker3
    hostname: worker3
    depends_on:
      - manager
    restart: on-failure
    command:
      [
        "elixir",
        "--name",
        "worker3@worker3",
        "--cookie",
        "squeeze_cookie",
        "-S",
        "mix",
        "squeezer.run",
        "--role",
        "worker",
        "--manager",
        "manager@manager"
      ]
